name: Post photos to Instagram

on:
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:   # ← allows you to “Run workflow” on demand

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug environment
        run: |
          echo "IG_ACCESS_TOKEN set? ${IG_ACCESS_TOKEN:+yes}"
          echo "IG_USER_ID      set? ${IG_USER_ID:+yes}"
          # show lengths (should be >0)
          echo -n "$IG_ACCESS_TOKEN" | wc -c | awk '{print "IG_ACCESS_TOKEN length:", $1}'
          echo -n "$IG_USER_ID"      | wc -c | awk '{print "IG_USER_ID length:     ", $1}'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run posting script
        env:
          RSS_URL:         https://me.chasen.dev/feed.xml
          IG_USER_ID:      ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
        run: |
          chmod +x .github/scripts/post_to_instagram.py
          .github/scripts/post_to_instagram.py

      - name: Commit updated state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posted.json
          git commit -m "Update posted state" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
