name: Post photos to Instagram

on:
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:   # ← allows you to “Run workflow” on demand

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      RSS_URL:         https://me.chasen.dev/feed.xml
      IG_USER_ID:      ${{ secrets.IG_USER_ID }}
      IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug secret presence
        run: |
          if [ -z "$IG_ACCESS_TOKEN" ]; then
            echo "::error::IG_ACCESS_TOKEN is empty"
          else
            echo "IG_ACCESS_TOKEN is present"
          fi

          if [ -z "$IG_USER_ID" ]; then
            echo "::error::IG_USER_ID is empty"
          else
            echo "IG_USER_ID is present"
          fi

          # show lengths (should be >0)
          echo -n "$IG_ACCESS_TOKEN" | wc -c | awk '{print "IG_ACCESS_TOKEN length:", $1}'
          echo -n "$IG_USER_ID"      | wc -c | awk '{print "IG_USER_ID length:     ", $1}'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run posting script
        run: |
          chmod +x .github/scripts/post_to_instagram.py
          .github/scripts/post_to_instagram.py

      - name: Commit updated state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posted.json
          git commit -m "Update posted state" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
